### PR TITLE
Fix the list of valid OS's so I can test the rancher installer

### PR DESCRIPTION
**Pull request by SvenDowideit**
Signed-off-by: Sven Dowideit <SvenDowideit@home.org.au>

### CODE REVIEW

**Comment by SvenDowideit** [comment]
mmm, i presume this should actually use https://github.com/packethost/packngo/blob/master/operatingsystems.go

gosh its hard to find out what values you want passed into the driver :(

**Comment by joshwget** [comment]
@SvenDowideit Might also need to add logic for RancherOS here too https://github.com/packethost/docker-machine-driver-packet/blob/master/driver.go#L94

**Comment by SvenDowideit** [comment]
added the rancher user for ssh as @joshwget noted

**Comment by crunchywelch** [comment]
@SvenDowideit does docker machine provisioner actually work with all these operating systems? last I checked, it only worked well with ubuntu 14.4

**Comment by joshwget** [comment]
Docker Machine contains provisioning logic for RancherOS, though I'm not sure how old it is. We're pretty interested in provisioning RancherOS on Packet so we'll test it and make any necessary fixes.

**Comment by SvenDowideit** [comment]
I've successfully provisioned ubuntu 16.04 - I'm guessing the answer is yes actually :)

without this change, you couldn't even try the other OS/distros.

**Comment by joshwget** [comment]
I was able to confirm that a RancherOS instance will be successfully provisioned with "rancher" as the value.

**Comment by crunchywelch** [comment]
lgtm thx

**Pull request merged**
