### PR TITLE
Query API for valid OS flavours

### PR DESCRIPTION
**Pull request by benjamb**

### CODE REVIEW

**Comment by benjamb** [comment]
Hrm, this looks to not be as easy as this, given different operating systems will have different ssh users.

**Comment by mmlb** [comment]
Maybe add a strings.HasPrefix for centos/ubuntu/debian/rancher? I don't think we should use the api to get back full list of OSes, since some may not support docker (freebsd?, virtuozzo, vmware, scilinux). But having a filter and os-discovery means we'll pick up on new versions coming in and old versions dropped.

**Comment by mmlb** [comment]
All the supported OSes should be good with root (need to double check rancheros though)

**Comment by benjamb** [comment]
@mmlb Now filtering based on a list of supported distros.

Tested with rancher and everything looks good. FreeBSD seems to not be supported by docker-machine (expects /etc/os-release to exist), so I've dropped support for it in the driver. Added OpenSUSE to the list after testing.

**Comment by mmlb** [comment]
now to dep'ify and make a new release.

**Comment by mmlb** [comment]
thanks @benjamb

**Comment by benjamb** [comment]
Np, cheers for the review!

**Pull request merged**
