### PR TITLE
Update CLI and device creation to take an array of facilities

### PR DESCRIPTION
**Pull request by benjamb**
Now checks whether the facilities have the availability to service a request.

Adds a new command line parameter to restrict the facilities checked by a list of facility codes.

### CODE REVIEW

**Comment by mmlb** [comment]
Hi @benjamb I don't think this PR should be merged. You can always run into TOCTOU problems, both false positive (check:available, provision:no-servers) and false negatives (check:non-available, if-try:server-available). Probably a better option is a specific http return code that can be used to guide the user into trying again later, or the library itself to sleep and try again. @patrickdevivo thoughts?

**Comment by benjamb** [comment]
@mmlb True. Though in the false positive case it would fail in the same way it would currently, the check absolutely does not guarantee that the device will be successfully be created, it is merely a check. For the false negatives, I could update this PR such that the server check only outputs a warning, and attempts to provision on the first specified facility regardless?

The primary motivation for this was to programmatically determine from the set of facilities, or from the facilities specified, which might be suitable to create a device on.

**Comment by mmlb** [comment]
@benjamb yeah that warning update sounds better. But I think even better would be to let the api make that decision itself, we've supported that in the api for a little while now. https://help.packet.net/en-us/article/19-batch-deployment.

**Comment by patrickdevivo** [comment]
just getting caught up here, if I'm reading the PR correctly, there was some similar discussion in the packngo library recently (https://github.com/packethost/packngo) about how to handle multiple facility selection. The API let's you pass `facility: ["ewr1", ...]` (or `facility: "ewr1"`), and packngo is updated to support the array format.

The API will place in whichever facility is first available, using the order of the array. Is this sufficient @benjamb?

**Comment by benjamb** [comment]
@mmlb Yes, that does sound much better.

@patrickdevivo Interesting, so AFAICT from the API docs, the base create endpoint can now take an array, or `"any"`? That will considerably reduce the size of this PR :)

**Comment by patrickdevivo** [comment]
@benjamb yep, and I believe you can include `any` in the array as well (but probably need to test to confirm)

**Comment by benjamb** [comment]
@patrickdevivo Aye, reads that way from the docs. Cool, I'll update (rewrite) this MR with that instead!

**Comment by benjamb** [comment]
@mmlb @patrickdevivo How's that looking now?

**Comment by patrickdevivo** [comment]
@benjamb nice! do we need to update the call to packngo as well to pass the facility as a `[]string`? https://github.com/packethost/docker-machine-driver-packet/blob/master/driver.go#L190

are there some kind of acceptance tests we could add to this repo potentially?

**Comment by benjamb** [comment]
@patrickdevivo I don't believe so, the packngo call was changed to just accept `[]string` in https://github.com/packethost/packngo/commit/576bf354c23ebb8e3b55984f25fbd21a8618e6bf.

It might be sane to somehow specify the version/sha of packngo the driver requires? Apparently `dep` looks like the tool to use for that.

Edit: **realises that's your commit**

**Comment by patrickdevivo** [comment]
@benjamb haha yep, we could update this to use `dep`

but I guess what I'm saying is doesn't this line need to be updated: https://github.com/packethost/docker-machine-driver-packet/blob/master/driver.go#L193 ?

**Comment by benjamb** [comment]
@patrickdevivo No, since I've already updated the type at line 32. I've also run this with a couple of different variations of facility arguments after fetching latest packngo.

**Comment by benjamb** [comment]
@mmlb @patrickdevivo Any update on this?

**Comment by benjamb** [comment]
@mmlb @patrickdevivo Any update on this?

**Comment by benjamb** [comment]
@mmlb @patrickdevivo Any update on this?

edit: sorry for the spam, I received errors on the previous attempts.

**Comment by patrickdevivo** [comment]
@benjamb sorry, I haven't had a chance to really look closely yet. this is on my todo list, unless @mmlb is able to take a look in the meantime, unfortunately I'm stretched a bit thin at the moment.

How exactly is this pegged to versions of the `packngo` library?

Also - I'd love to see some acceptance tests for this repo that we could run for PRs/updates, but that's a broader discussion

**Comment by benjamb** [comment]
@patrickdevivo Ah, no worries. Just hadn't received an update in a while and was wondering what the situation was.

WRT locking dependency versions, I feel that's a little out of the scope of this particular PR. I've limited experience with go projects as it is, much less managing dependencies for any. While `dep` appears to be a popular choice, I really don't like the idea of importing the entirety of a project in-tree, I'd much prefer a solution that made use of git-submodule, or perhaps git-subrepo.

**Comment by jasmingacic** [comment]
@amenowanna can you give us some feedback on this

**Comment by jasmingacic** [comment]
I'm going to close this as it is staled.

**Comment by benjamb** [comment]
@jasmingacic Decided to give this a rebase in case someone might consider it to be useful, though I don't use the driver any more so I haven't given it a test.

**Comment by benjamb** [comment]
@jasmingacic Since the PR is closed, you can see the changes here: https://github.com/packethost/docker-machine-driver-packet/compare/master...benjamb:capacity
I'll open a new one if it seems worthwhile.

**Pull request closed without merging**
